# Generated by Django 3.2.7 on 2021-10-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penerima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Required. Inform a valid email address', max_length=254)),
                ('username', models.CharField(help_text='Required. Inform a valid username', max_length=30)),
                ('password', models.CharField(help_text='Required. Inform a valid password.', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Penyedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Required. Inform a valid email address', max_length=254)),
                ('username', models.CharField(help_text='Required. Inform a valid username', max_length=30)),
                ('password', models.CharField(help_text='Required. Inform a valid password.', max_length=30)),
            ],
        ),
    ]
