# Generated by Django 3.2.8 on 2021-10-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211025_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='', max_length=30),
        ),
    ]
