# Generated by Django 3.2.7 on 2021-11-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaksin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=30)),
                ('tanggal', models.DateField(null=True)),
                ('waktu', models.TimeField()),
                ('jumlah', models.SmallIntegerField()),
                ('penyedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.penyedia')),
            ],
        ),
    ]
