# Generated by Django 3.2.7 on 2021-11-05 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambah_vaksin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaksin',
            name='waktu',
        ),
        migrations.AlterField(
            model_name='vaksin',
            name='tanggal',
            field=models.DateField(default=datetime.date(2021, 11, 5)),
        ),
    ]
