# Generated by Django 3.2.7 on 2021-10-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambah_vaksin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaksin',
            name='tanggal',
            field=models.DateField(null=True),
        ),
    ]
