# Generated by Django 3.2.7 on 2021-11-03 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLengkap', models.CharField(max_length=25)),
                ('NIK', models.IntegerField(unique=True)),
                ('tanggalLahir', models.DateField()),
                ('jenisKelamin', models.CharField(max_length=10)),
                ('nomorHandphone', models.IntegerField()),
                ('alamat', models.CharField(max_length=100)),
                ('superUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penyedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaInstansi', models.CharField(max_length=50, unique=True)),
                ('kota', models.CharField(max_length=20)),
                ('nomorTelepon', models.IntegerField()),
                ('alamat', models.CharField(max_length=100)),
                ('superUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
