# Generated by Django 3.2.9 on 2021-11-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyedia',
            name='nomorTelepon',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='NIK',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nomorHandphone',
            field=models.CharField(max_length=12),
        ),
    ]
