# Generated by Django 3.2.8 on 2021-10-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penyedia',
            old_name='telp',
            new_name='telepon',
        ),
        migrations.RenameField(
            model_name='peserta',
            old_name='dob',
            new_name='Birthdate',
        ),
        migrations.RenameField(
            model_name='peserta',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='peserta',
            old_name='hp',
            new_name='HP',
        ),
        migrations.RenameField(
            model_name='peserta',
            old_name='nik',
            new_name='NIK',
        ),
    ]
