# Generated by Django 3.2.8 on 2021-10-25 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_auto_20211024_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penyedia',
            old_name='address',
            new_name='alamat',
        ),
        migrations.RenameField(
            model_name='penyedia',
            old_name='city',
            new_name='kota',
        ),
        migrations.RenameField(
            model_name='penyedia',
            old_name='instansi',
            new_name='namaInstansi',
        ),
        migrations.RenameField(
            model_name='penyedia',
            old_name='telepon',
            new_name='nomorTelepon',
        ),
        migrations.RenameField(
            model_name='peserta',
            old_name='address',
            new_name='alamat',
        ),
        migrations.RenameField(
            model_name='peserta',
            old_name='Gender',
            new_name='jenisKelamin',
        ),
        migrations.RenameField(
            model_name='peserta',
            old_name='fullName',
            new_name='namaLengkap',
        ),
        migrations.RenameField(
            model_name='peserta',
            old_name='HP',
            new_name='nomorHandphone',
        ),
        migrations.RenameField(
            model_name='peserta',
            old_name='Birthdate',
            new_name='tanggalLahir',
        ),
    ]
