# Generated by Django 3.2.8 on 2021-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_auto_20211025_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyedia',
            name='alamat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='penyedia',
            name='namaInstansi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='alamat',
            field=models.CharField(max_length=100),
        ),
    ]
