# Generated by Django 3.2.7 on 2021-10-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0004_auto_20211026_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='NIK',
            field=models.IntegerField(unique=True),
        ),
    ]
