# Generated by Django 3.2.7 on 2021-10-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211025_2150'),
        ('biodata', '0008_alter_peserta_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='superUser',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
