# Generated by Django 3.2.8 on 2021-10-27 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodata', '0012_alter_peserta_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyedia',
            name='superUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penyedia',
            name='namaInstansi',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
