# Generated by Django 3.2.7 on 2021-10-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biodata', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalVaksin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kota', models.CharField(max_length=30)),
                ('tanggal', models.DateField(null=True)),
                ('jenis_vaksin', models.CharField(default='', max_length=30)),
                ('tempat', models.CharField(max_length=30)),
                ('penerima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.peserta')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.penyedia')),
            ],
        ),
    ]
