# Generated by Django 3.2.7 on 2021-10-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalVaksin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kota', models.CharField(max_length=30)),
                ('tanggal', models.DateField()),
                ('jenis_vaksin', models.CharField(max_length=30)),
                ('tempat', models.CharField(max_length=30)),
                ('waktu', models.TimeField()),
            ],
        ),
    ]
