# Generated by Django 3.2.7 on 2021-10-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='jenis_vaksin',
            field=models.CharField(choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='kota',
            field=models.CharField(choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='tanggal',
            field=models.CharField(choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='tempat',
            field=models.CharField(choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='waktu',
            field=models.CharField(choices=[], max_length=30),
        ),
    ]
