# Generated by Django 3.2.8 on 2021-11-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='jenis_vaksin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='kota',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='tempat',
            field=models.CharField(max_length=255),
        ),
    ]
