# Generated by Django 3.2.7 on 2021-11-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '__first__'),
        ('daftar_vaksin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='jenis_vaksin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='kota',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='penerima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.peserta'),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.penyedia'),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='tanggal',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='tempat',
            field=models.CharField(max_length=255),
        ),
    ]
