# Generated by Django 3.2.7 on 2021-10-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0013_auto_20211027_0842'),
        ('daftar_vaksin', '0002_auto_20211027_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalvaksin',
            name='penerima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.peserta'),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='jenis_vaksin',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='kota',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='tanggal',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='tempat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biodata.penyedia'),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='waktu',
            field=models.CharField(max_length=30),
        ),
    ]
