# Generated by Django 3.2.7 on 2021-10-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksin', '0004_auto_20211028_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwalvaksin',
            old_name='jenis_vaksin',
            new_name='jenis',
        ),
        migrations.RemoveField(
            model_name='jadwalvaksin',
            name='waktu',
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
