# Generated by Django 3.2.7 on 2021-10-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksin', '0005_auto_20211028_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwalvaksin',
            old_name='jenis',
            new_name='jenis_vaksin',
        ),
    ]
