# Generated by Django 3.2.7 on 2021-10-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksin', '0006_rename_jenis_jadwalvaksin_jenis_vaksin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='tanggal',
            field=models.DateField(null=True),
        ),
    ]
