# Generated by Django 3.2.7 on 2021-10-29 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0013_auto_20211027_0842'),
        ('daftar_vaksin', '0007_alter_jadwalvaksin_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalvaksin',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.penyedia'),
        ),
        migrations.AlterField(
            model_name='jadwalvaksin',
            name='tempat',
            field=models.CharField(max_length=30),
        ),
    ]
