# Generated by Django 3.2.8 on 2021-10-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_discussion_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.discussion'),
        ),
    ]
