# Generated by Django 3.2.8 on 2021-10-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211028_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='updated_at',
        ),
    ]
